### ISSUE TITLE
Player sent to black screen after Rufus gives key 

### ISSUE THREAD

**Issue by YungRees** [sabarrett/wayward-colony-issues#1]
Bug: Player sent to black screen after Rufus gives key.

Symptoms : Black screen. Menu still accessible. "Rufus' Room Key" item  deposited in inventory. Can "open" Shaun's paper but the image no longer appears

Steps to recreate : Player must have taken personal exam, fixed the bridge, opened the Icarus Door. and replaced the wooden idol. (Not in sequence)

**Comment by YungRees** [comment]
Update : On same save file have linked the "Chariot" computer with the Radio, have collected 3 idols and returned them. Same issue at same stage

**Comment by sabarrett** [comment]
I also get this, having added 2 idols and having connected whatever computer is closest to the entrance of that tower floor (Orion? Osrius? Idk)

**Comment by YungRees** [comment]
Update : I believe this is unavoidable. Full list of activities completed prior to Rufus dream below

- Used Crowbar to get Tuna for Cat, opened Bast (empty chest, see other bug)
- Retrieved Bird for "Icarus"
- Lied several times for "Liar"
- Used 2 lumber to build bridge
- Used Screwdriver to get scrap of paper
- Used radio to decipher "Chariot" and "Osirus" computers
- Used Copper key to steal Shaun's journal. 
-- also tried entering Rufus' dream without Shaun's journal, no change
- Placed 3 wooden idols. Because this happens on the third day, it is impossible to build the bridge and get 1 coin, meaning all 4 Idols cannot be retrieved in a single playthrough before crash
