### ISSUE TITLE
Too easy to accidentally slide back over bridge in Rufus' dream

### ISSUE THREAD

**Issue by sabarrett** [sabarrett/wayward-colony-issues#12]
As pictured below, if the player walks straight up they'll move across the bridge to the right. Maybe redesign layout so it's hard to approach from the top or bottom?

![image](https://github.com/sabarrett/wayward-colony-issues/assets/4325000/c9f79ea5-2c7a-4d86-b107-0442f2a35ff8)

**Comment by CaseyPau** [comment]
ehhh I disagree. It penalizes the player (very slightly) for not paying attention to the mechanics of the level, it's the last bridge you have to cross so you should know how it works.

**Comment by sabarrett** [comment]
It's not a big deal, but I thought the rule was "the bridge keeps you moving in whatever direction you're walking", but really it sends you in a specific direction. So when you touch the bridge from below it unintuitively sends you off the the right. This is the only tile where you can approach the bridge from the "wrong" direction -- everywhere else you necessarily move in the direction you were already moving
