### ISSUE TITLE
Permanent black screen after second classroom lesson

### ISSUE THREAD

**Issue by sabarrett** [sabarrett/wayward-colony-issues#2]
- No wooden idols
- Did Icarian and Liars doors
- After second classroom test, game enters black screen after player is teleported to woods
- Calling "$gameScreen.startFadeIn()" fixes it, so presumably there's Fade In in a script that's not executing?

**Comment by sabarrett** [comment]
Also occured after following lesson on same playthrough

**Comment by CaseyPau** [comment]
Ah! Took me a minute to figure this one out. This occurs if the player goes into the woods BEFORE the lesson - event was set up to trigger once and then self-switch itself. fixed
