### ISSUE TITLE
Game stays in sepia after viewing surveillance footage

### ISSUE THREAD

**Issue by sabarrett** [sabarrett/wayward-colony-issues#6]
In first dream sequence (night after Rufus is scolded), you can view surveillance camera-style footage, which tones the screen sepia. After exiting this, the game is still in sepia:

![image](https://github.com/sabarrett/wayward-school/assets/4325000/4461e5e8-5dd9-4daa-aa01-d994405ad30b)

**Comment by CaseyPau** [comment]
fixed.
