### ISSUE TITLE
Player able to steal Shaun's journal at any point

### ISSUE THREAD

**Issue by YungRees** [sabarrett/wayward-colony-issues#8]
Bug :  Player able to steal Shaun's journal at any point

Intended strat : Get copper key from Gate of Liar to open Commissary Door/Steal Journal

Skip : interacting with the journal across the desk allows you to steal the journal the second you enter the school 

Steps to recreate : interact with the desk in front of the journal, profit.

**Comment by CaseyPau** [comment]
fixed

**Comment by sabarrett** [comment]
I still have this -- is the new version not uploaded?

**Comment by CaseyPau** [comment]
yeah it's the OLD PATCH
